# Generated by Django 2.2 on 2019-04-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('dni', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('studies', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
