# Generated by Django 2.2 on 2019-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.CharField(default='nan', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='dni',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='nan', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='nan', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='nan', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(default='nan', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='studies',
            field=models.CharField(default='nan', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='nan', max_length=10),
        ),
    ]
