# Generated by Django 2.2 on 2019-04-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190428_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='nan', max_length=20),
        ),
    ]
