# Generated by Django 2.2 on 2019-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190428_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default='nan', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='cp',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='users',
            name='cuil',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='users',
            name='interest',
            field=models.CharField(default='nan', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(default='nan', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=123),
        ),
        migrations.AddField(
            model_name='users',
            name='province',
            field=models.CharField(default='nan', max_length=15),
        ),
    ]
