# Generated by Django 2.2 on 2019-05-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190430_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cuil',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='dni',
            field=models.CharField(default='nan', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='nan', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='nan', max_length=100),
        ),
    ]
